main: dp.warloise.DifficultyPlugin
version: 1.3.0
name: DifficultyPlugin
author: Warloise
api-version: 1.13

commands:
  difficulty-reload:
    description: Recarga la configuración del plugin
    usage: /difficulty-reload
    permission: difficultyreload.reloadconfig
  diff-time:
    description: Configura el tiempo del plugin
    usage: /diff-time
    permission: difftime.config
  difficulty-save:
    description: Guarda la informacion del game
    usage: /difficulty-save
    permission: difficultysave.param
  menueleccion:
    description: Muestra 3 items a elegir para la votación
    usage: /menueleccion
    permission: menueleccion.config
  selectionElection:
    description: Activa el evento que quieras.
    usage: /selectionElection
    permission: selectionelection.config
  corruptedEvents:
    description: Activar o desactivar los eventos corruptos
    usage: /corruptedEvents
    permission: corruptedevents.config